id: lcll-config-info

info:
  name: lcll-config-info
  author: HB
  severity: high

http:
  - raw:
    - |
      GET /config/config%20bak.txt HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3
      Accept: */*

    matchers:
      - type: dsl
        dsl:
          - 'status_code==200'